# Applies ONLY to product-service

  # Applies ONLY to product-service
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/product_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8082
management:
  tracing:
    sampling:
      probability: 1.0  # 100% tracing
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans  
  




    
    
    
  
  
 

  
